DEFINE_CHECK_FUNCTION(ah,         0,   check_point_ah)
DEFINE_CHECK_FUNCTION(bh,         1,   check_point_bh)
DEFINE_CHECK_FUNCTION(ch,         2,   check_point_ch)
DEFINE_CHECK_FUNCTION(dh,         3,   check_point_dh)
DEFINE_CHECK_FUNCTION(al,         4,   check_point_al)
DEFINE_CHECK_FUNCTION(bl,         5,   check_point_bl)
DEFINE_CHECK_FUNCTION(cl,         6,   check_point_cl)
DEFINE_CHECK_FUNCTION(dl,         7,   check_point_dl)

DEFINE_CHECK_FUNCTION(ax,         8,   check_point_ax)
DEFINE_CHECK_FUNCTION(bx,         9,   check_point_bx)
DEFINE_CHECK_FUNCTION(cx,         10,  check_point_cx)
DEFINE_CHECK_FUNCTION(dx,         11,  check_point_dx)
DEFINE_CHECK_FUNCTION(si,         12,  check_point_si)
DEFINE_CHECK_FUNCTION(di,         13,  check_point_di)
DEFINE_CHECK_FUNCTION(sp,         14,  check_point_sp)
DEFINE_CHECK_FUNCTION(bp,         15,  check_point_bp)

DEFINE_CHECK_FUNCTION(eax,        16,  check_point_eax)
DEFINE_CHECK_FUNCTION(ebx,        17,  check_point_ebx)
DEFINE_CHECK_FUNCTION(ecx,        18,  check_point_ecx)
DEFINE_CHECK_FUNCTION(edx,        19,  check_point_edx)
DEFINE_CHECK_FUNCTION(esi,        20,  check_point_esi)
DEFINE_CHECK_FUNCTION(edi,        21,  check_point_edi)
DEFINE_CHECK_FUNCTION(esp,        22,  check_point_esp)
DEFINE_CHECK_FUNCTION(ebp,        23,  check_point_ebp)

DEFINE_CHECK_FUNCTION(cs,         24,  check_point_cs)
DEFINE_CHECK_FUNCTION(ds,         25,  check_point_ds)
DEFINE_CHECK_FUNCTION(ss,         26,  check_point_ss)
DEFINE_CHECK_FUNCTION(es,         27,  check_point_es)
DEFINE_CHECK_FUNCTION(fs,         28,  check_point_fs)
DEFINE_CHECK_FUNCTION(gs,         29,  check_point_gs)

DEFINE_CHECK_FUNCTION(eflags,     30,  check_point_eflags)

DEFINE_CHECK_FUNCTION(x86_state,  31,  check_point_x86_state)

DEFINE_CHECK_FUNCTION(st0,  32,  check_point_st0)
DEFINE_CHECK_FUNCTION(st1,  33,  check_point_st1)
DEFINE_CHECK_FUNCTION(st2,  34,  check_point_st2)
DEFINE_CHECK_FUNCTION(st3,  35,  check_point_st3)
DEFINE_CHECK_FUNCTION(st4,  36,  check_point_st4)
DEFINE_CHECK_FUNCTION(st5,  37,  check_point_st5)
DEFINE_CHECK_FUNCTION(st6,  38,  check_point_st6)
DEFINE_CHECK_FUNCTION(st7,  39,  check_point_st7)

DEFINE_CHECK_FUNCTION(mm0, 40, check_point_mm0)
DEFINE_CHECK_FUNCTION(mm1, 41, check_point_mm1)
DEFINE_CHECK_FUNCTION(mm2, 42, check_point_mm2)
DEFINE_CHECK_FUNCTION(mm3, 43, check_point_mm3)
DEFINE_CHECK_FUNCTION(mm4, 44, check_point_mm4)
DEFINE_CHECK_FUNCTION(mm5, 45, check_point_mm5)
DEFINE_CHECK_FUNCTION(mm6, 46, check_point_mm6)
DEFINE_CHECK_FUNCTION(mm7, 47, check_point_mm7)

DEFINE_CHECK_FUNCTION(fcw,  48,  check_point_fcw)
DEFINE_CHECK_FUNCTION(fsw,  49,  check_point_fsw)
DEFINE_CHECK_FUNCTION(ftw,  50,  check_point_ftw)
DEFINE_CHECK_FUNCTION(ffop,  51,  check_point_ffop)
DEFINE_CHECK_FUNCTION(ffdp,  52,  check_point_ffdp)
DEFINE_CHECK_FUNCTION(ffip,  53,  check_point_ffip)
